### ISSUE TITLE
Debug for Tom Flint issue

### ISSUE THREAD

**Issue by TFlint82** [cagnulein/QZCompanionNordictrackTreadmill#99]
/storage/emulated/0/Documents/QZ/debug-Thu_Apr_18_16_33_46_2024.log

**Comment by cagnulein** [comment]
Hi @TFlint82 you need to attach the file

**Comment by cagnulein** [comment]
Send me to my email if you can't attach it

Roberto.viola83@gmail.com 

Include the description of the issue or the original ticket link

**Comment by TFlint82** [comment]
Submitted a new Bug post which allowed me to add

**Comment by cagnulein** [comment]
Got the issue. You configured qz like a treadmill instead of a bike.

Remove completely the ip from the nordictrack 2950 ip setting and press OK (be sure to don't leave any space neither)

Then put the ip instead here in the bike section, nordictrack bike 

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/48216/456bd01c-b2f3-450a-b3cd-799ecd84502c)

let me know

**Comment by cagnulein** [comment]
@TFlint82 any news?
